# generated by datamodel-codegen:
#   filename:  https://raw.githubusercontent.com/ctfpilot/challenge-schema/refs/heads/main/schema.json
#   timestamp: 2025-11-26T22:40:56+00:00

from __future__ import annotations

from enum import Enum
from typing import Optional, Sequence, Union

from pydantic import BaseModel, Field, RootModel
from typing_extensions import Annotated


class Tag(RootModel[str]):
    root: Annotated[
        str, Field(max_length=50, min_length=1, pattern='^[a-zA-Z0-9-_:;? ]+$')
    ]


class Prerequisite(RootModel[str]):
    root: Annotated[str, Field(max_length=100, min_length=1, pattern='^[a-z0-9-]+$')]
    """
    The prerequisites of the challenge. Must be the slugs of the challenges.
    """


class Category(Enum):
    web = 'web'
    forensics = 'forensics'
    rev = 'rev'
    crypto = 'crypto'
    pwn = 'pwn'
    boot2root = 'boot2root'
    osint = 'osint'
    misc = 'misc'
    blockchain = 'blockchain'
    mobile = 'mobile'
    test = 'test'


class Difficulty(Enum):
    beginner = 'beginner'
    easy = 'easy'
    easy_medium = 'easy-medium'
    medium = 'medium'
    medium_hard = 'medium-hard'
    hard = 'hard'
    very_hard = 'very-hard'
    insane = 'insane'


class Type(Enum):
    static = 'static'
    shared = 'shared'
    instanced = 'instanced'


class InstancedType(Enum):
    web = 'web'
    tcp = 'tcp'
    none = 'none'


class InstancedName(RootModel[str]):
    root: Annotated[
        str,
        Field(
            examples=['example-challenge'],
            max_length=50,
            min_length=1,
            pattern='^[a-z0-9-]+$',
        ),
    ]
    """
    The slug of the instanced challenge. This is applicable if the `type` is `instanced` and another instance is used instead of itself. May also be itself to specify that the challenge is instanced but does not use another instance.
    """


class InstancedSubdomain(RootModel[str]):
    root: Annotated[
        str,
        Field(
            examples=['web', 'admin', 'api', 'tcp:service', 'web:dashboard'],
            max_length=10,
            min_length=0,
            pattern='^((web|tcp):)?[a-z0-9-]+$',
        ),
    ]
    """
    The subdomain of the instanced challenge. This is applicable if the `type` is `instanced` and the challenge is hosted on a server. It will be prefixed with the instanced domain. Each entry may optionally be prefixed with `web:` or `tcp:` (e.g., `web:api`, `tcp:service`, or just `admin`). The prefix indicates the protocol associated with the subdomain.
    """


class Flag(RootModel[str]):
    root: Annotated[
        str,
        Field(
            examples=[
                'flag{flag}',
                ['flag{flag1}', 'flag{flag2}'],
                [
                    {'flag': 'flag{flag1}', 'case_sensitive': True},
                    {'flag': 'flag{flag2}', 'case_sensitive': False},
                ],
            ],
            max_length=1000,
            min_length=4,
            pattern='^(\\w{2,10}\\{[^}]*\\}|dynamic|null)$',
        ),
    ]
    """
    The flag of the challenge. May be a single string or an array of strings. Each may be 'dynamic', 'null', or a flag like 'flag{...}'. `flag` may be replaced with between 2 and 10 word chars. If case sensitivity is not explicitly specified, the flag is case sensitive.
    """


class Flag11(RootModel[str]):
    root: Annotated[
        str,
        Field(
            max_length=1000,
            min_length=4,
            pattern='^(\\w{2,10}\\{[^}]*\\}|dynamic|null)$',
        ),
    ]


class Flag12(BaseModel):
    flag: Annotated[
        str,
        Field(
            max_length=1000,
            min_length=4,
            pattern='^(\\w{2,10}\\{[^}]*\\}|dynamic|null)$',
        ),
    ]
    case_sensitive: Annotated[Optional[bool], Field(examples=[True, False])] = True
    """
    Whether the flag is case sensitive or not. If false, the flag will be checked case insensitively. Default is true.
    """


class Flag1(RootModel[Sequence[Union[Flag11, Flag12]]]):
    root: Annotated[
        Sequence[Union[Flag11, Flag12]],
        Field(
            examples=[
                'flag{flag}',
                ['flag{flag1}', 'flag{flag2}'],
                [
                    {'flag': 'flag{flag1}', 'case_sensitive': True},
                    {'flag': 'flag{flag2}', 'case_sensitive': False},
                ],
            ],
            min_length=1,
        ),
    ]
    """
    The flag of the challenge. May be a single string or an array of strings. Each may be 'dynamic', 'null', or a flag like 'flag{...}'. `flag` may be replaced with between 2 and 10 word chars. If case sensitivity is not explicitly specified, the flag is case sensitive.
    """


class DockerfileLocation(BaseModel):
    location: Annotated[
        str, Field(examples=['src/Dockerfile'], pattern='^[a-zA-Z0-9-_/.]+$')
    ]
    """
    The location of the Dockerfile relative to the challenge directory
    """
    context: Annotated[str, Field(examples=['src/'], pattern='^[a-zA-Z0-9-_/.]+$')]
    """
    The context of the Dockerfile relative to the challenge directory
    """
    identifier: Annotated[Optional[str], Field(examples=['None', None])] = None
    """
    The identifier of the Dockerfile to suffix the docker image with (None, null, or empty string for no suffix)
    """


class Model(BaseModel):
    version: Annotated[
        Optional[str],
        Field(
            examples=['1', '1.0', '1.0.0'], pattern='^(\\d+\\.)?(\\d+\\.)?(\\*|\\d+)$'
        ),
    ] = '1'
    """
    The version of the challenge schema
    """
    enabled: bool
    """
    Whether the challenge is enabled or not. If disabled, this forces the challenge to not be deployed or interacted with.
    Should only be false if the challenge is not ready.
    """
    name: Annotated[
        str, Field(examples=['Example Challenge'], max_length=50, min_length=1)
    ]
    """
    The name of the challenge
    """
    slug: Annotated[
        str,
        Field(
            examples=['example-challenge'],
            max_length=50,
            min_length=1,
            pattern='^[a-z0-9-]+$',
        ),
    ]
    """
    The slug of the challenge
    """
    author: Annotated[str, Field(examples=['John Smith'], max_length=100, min_length=1)]
    """
    The author of the challenge
    """
    tags: Optional[Sequence[Tag]] = []
    """
    Tags for the challenge. Used for filtering and searching.
    """
    prerequisites: Optional[Sequence[Prerequisite]] = None
    """
    Required challenges to solve before this challenge can be displayed
    """
    category: Category
    """
    The category of the challenge
    """
    difficulty: Difficulty
    """
    The difficulty of the challenge
    """
    type: Type
    """
    The type of challenge.
    Static challenges represent challenges utilizing delivered files and information.
    Shared challenges represent challenges that are hosted on a server and shared among multiple teams.
    Instanced challenges represent challenges that are hosted on a server and are unique to each user/team.
    """
    instanced_type: Optional[InstancedType] = InstancedType.none
    """
    The type of instanced challenge.
    Defines how users interact with the challenge.
    """
    instanced_name: Optional[InstancedName] = None
    instanced_subdomains: Annotated[
        Optional[Sequence[InstancedSubdomain]],
        Field(examples=[['web', 'admin', 'api'], ['api']], max_length=5, min_length=0),
    ] = []
    """
    The subdomains of the instanced challenge. This is applicable if the `type` is `instanced` and the challenge is hosted on a server. It will be prefixed with the instanced domain.
    """
    connection: Annotated[
        Optional[str],
        Field(
            examples=['http://example.com', 'nc example.com 1337', 'nc ${host} 1337'],
            max_length=255,
        ),
    ] = None
    """
    The connection string for the challenge. This is applicable if the `type` is not `instanced` and the challenge is hosted on a server. It is used to display connection information for the challenge. You can use the variable `${host}` in the string, which will be replaced with the website domain when rendered.
    """
    points: Annotated[Optional[int], Field(ge=1, le=10000)] = 1000
    """
    The amount of points the challenge is worth from the start
    """
    decay: Annotated[Optional[int], Field(ge=0, le=10000)] = 75
    """
    The percentage of points lost over time
    """
    min_points: Annotated[Optional[int], Field(ge=1, le=1000)] = 100
    """
    The minimum amount of points the challenge can be worth. min_points must be less than or equal to points.
    """
    flag: Annotated[
        Union[Flag, Flag1],
        Field(
            examples=[
                'flag{flag}',
                ['flag{flag1}', 'flag{flag2}'],
                [
                    {'flag': 'flag{flag1}', 'case_sensitive': True},
                    {'flag': 'flag{flag2}', 'case_sensitive': False},
                ],
            ]
        ),
    ]
    """
    The flag of the challenge. May be a single string or an array of strings. Each may be 'dynamic', 'null', or a flag like 'flag{...}'. `flag` may be replaced with between 2 and 10 word chars. If case sensitivity is not explicitly specified, the flag is case sensitive.
    """
    description_location: Annotated[
        Optional[str],
        Field(examples=['description.md'], pattern='^[a-zA-Z0-9-_/.]+\\.md$'),
    ] = 'description.md'
    """
    The location of the description file relative to the challenge directory
    """
    dockerfile_locations: Optional[Sequence[DockerfileLocation]] = []
    """
    The locations of the Dockerfiles relative to the challenge directory.
    Multiple Dockerfiles can be specified if the challenge requires multiple images.
    """
    handout_dir: Annotated[
        Optional[str], Field(examples=['handout'], pattern='^[a-zA-Z0-9-_/]+$')
    ] = 'handout'
    """
    The location of the handout directory relative to the challenge directory. Handout directory contains all files that are handed out to users (zipped to a single file that are stored in <category>_<slug>.zip in the files directory).
    """
