# generated by datamodel-codegen:
#   filename:  https://raw.githubusercontent.com/ctfpilot/page-schema/refs/heads/main/schema.json
#   timestamp: 2025-11-26T22:41:04+00:00

from __future__ import annotations

from enum import Enum
from typing import Optional

from pydantic import BaseModel, Field
from typing_extensions import Annotated


class Format(Enum):
    markdown = 'markdown'
    html = 'html'


class Model(BaseModel):
    version: Annotated[
        Optional[str],
        Field(
            examples=['1', '1.0', '1.0.0'], pattern='^(\\d+\\.)?(\\d+\\.)?(\\*|\\d+)$'
        ),
    ] = '1'
    """
    The version of the page schema
    """
    enabled: bool
    """
    Whether the page is enabled or not. If disabled, this forces the page to not be deployed or interacted with.
    """
    slug: Annotated[
        str,
        Field(
            examples=['example-page'],
            max_length=50,
            min_length=1,
            pattern='^[a-z0-9-]+$',
        ),
    ]
    """
    The slug of the page
    """
    title: Annotated[
        str, Field(examples=['Example Page'], max_length=100, min_length=1)
    ]
    """
    The title of the page
    """
    route: Annotated[
        str, Field(examples=['/example-page'], max_length=100, min_length=1)
    ]
    """
    The route of the page, used for navigation
    """
    content: Annotated[
        str,
        Field(
            examples=['page.md', 'README.md', 'example-page.md'],
            max_length=255,
            min_length=1,
            pattern='^([a-zA-Z0-9-_./]+\\.(md|html))$',
        ),
    ]
    """
    The path to the content file for the page. This file should be located in the repository and contain the content of the page in Markdown or HTML format.
    """
    auth: Optional[bool] = False
    """
    Whether the page requires authentication to view. If true, only authenticated users can access the page.
    """
    draft: Optional[bool] = False
    """
    Whether the page is a draft or not. If true, this indicates that the page is still under development and not ready for public viewing.
    """
    format: Format
    """
    The format of the page content. Can be either 'markdown' or 'html'. This determines how the content is rendered on the page.
    """
