# generated by datamodel-codegen:
#   filename:  https://raw.githubusercontent.com/ctfpilot/challenge-schema/refs/heads/main/schema.json
#   timestamp: 2025-11-26T22:22:46+00:00

from __future__ import annotations

from enum import Enum
from typing import List, Optional, Union

from pydantic import BaseModel, Field, conint, constr


class Prerequisite(BaseModel):
    __root__: constr(regex=r'^[a-z0-9-]+$', min_length=1, max_length=100) = Field(
        ...,
        description='The prerequisites of the challenge. Must be the slugs of the challenges.',
    )


class Category(Enum):
    web = 'web'
    forensics = 'forensics'
    rev = 'rev'
    crypto = 'crypto'
    pwn = 'pwn'
    boot2root = 'boot2root'
    osint = 'osint'
    misc = 'misc'
    blockchain = 'blockchain'
    mobile = 'mobile'
    test = 'test'


class Difficulty(Enum):
    beginner = 'beginner'
    easy = 'easy'
    easy_medium = 'easy-medium'
    medium = 'medium'
    medium_hard = 'medium-hard'
    hard = 'hard'
    very_hard = 'very-hard'
    insane = 'insane'


class Type(Enum):
    static = 'static'
    shared = 'shared'
    instanced = 'instanced'


class InstancedType(Enum):
    web = 'web'
    tcp = 'tcp'
    none = 'none'


class InstancedSubdomain(BaseModel):
    __root__: constr(
        regex=r'^((web|tcp):)?[a-z0-9-]+$', min_length=0, max_length=10
    ) = Field(
        ...,
        description='The subdomain of the instanced challenge. This is applicable if the `type` is `instanced` and the challenge is hosted on a server. It will be prefixed with the instanced domain. Each entry may optionally be prefixed with `web:` or `tcp:` (e.g., `web:api`, `tcp:service`, or just `admin`). The prefix indicates the protocol associated with the subdomain.',
        examples=['web', 'admin', 'api', 'tcp:service', 'web:dashboard'],
    )


class Flag(BaseModel):
    flag: constr(
        regex=r'^(\w{2,10}\{[^}]*\}|dynamic|null)$', min_length=4, max_length=1000
    )
    case_sensitive: Optional[bool] = Field(
        True,
        description='Whether the flag is case sensitive or not. If false, the flag will be checked case insensitively. Default is true.',
        examples=[True, False],
    )


class DockerfileLocation(BaseModel):
    location: constr(regex=r'^[a-zA-Z0-9-_/.]+$') = Field(
        ...,
        description='The location of the Dockerfile relative to the challenge directory',
        examples=['src/Dockerfile'],
    )
    context: constr(regex=r'^[a-zA-Z0-9-_/.]+$') = Field(
        ...,
        description='The context of the Dockerfile relative to the challenge directory',
        examples=['src/'],
    )
    identifier: Optional[str] = Field(
        None,
        description='The identifier of the Dockerfile to suffix the docker image with (None, null, or empty string for no suffix)',
        examples=['None', None],
    )


class Model(BaseModel):
    version: Optional[constr(regex=r'^(\d+\.)?(\d+\.)?(\*|\d+)$')] = Field(
        '1',
        description='The version of the challenge schema',
        examples=['1', '1.0', '1.0.0'],
    )
    enabled: bool = Field(
        ...,
        description='Whether the challenge is enabled or not. If disabled, this forces the challenge to not be deployed or interacted with.\nShould only be false if the challenge is not ready.',
    )
    name: constr(min_length=1, max_length=50) = Field(
        ..., description='The name of the challenge', examples=['Example Challenge']
    )
    slug: constr(regex=r'^[a-z0-9-]+$', min_length=1, max_length=50) = Field(
        ..., description='The slug of the challenge', examples=['example-challenge']
    )
    author: constr(min_length=1, max_length=100) = Field(
        ..., description='The author of the challenge', examples=['John Smith']
    )
    tags: Optional[
        List[constr(regex=r'^[a-zA-Z0-9-_:;? ]+$', min_length=1, max_length=50)]
    ] = Field(
        [], description='Tags for the challenge. Used for filtering and searching.'
    )
    prerequisites: Optional[List[Prerequisite]] = Field(
        None,
        description='Required challenges to solve before this challenge can be displayed',
        unique_items=True,
    )
    category: Category = Field(..., description='The category of the challenge')
    difficulty: Difficulty = Field(..., description='The difficulty of the challenge')
    type: Type = Field(
        ...,
        description='The type of challenge.\nStatic challenges represent challenges utilizing delivered files and information.\nShared challenges represent challenges that are hosted on a server and shared among multiple teams.\nInstanced challenges represent challenges that are hosted on a server and are unique to each user/team.',
    )
    instanced_type: Optional[InstancedType] = Field(
        'none',
        description='The type of instanced challenge.\nDefines how users interact with the challenge.',
    )
    instanced_name: Optional[
        constr(regex=r'^[a-z0-9-]+$', min_length=1, max_length=50)
    ] = None
    instanced_subdomains: Optional[List[InstancedSubdomain]] = Field(
        [],
        description='The subdomains of the instanced challenge. This is applicable if the `type` is `instanced` and the challenge is hosted on a server. It will be prefixed with the instanced domain.',
        examples=[['web', 'admin', 'api'], ['api']],
        max_items=5,
        min_items=0,
        unique_items=True,
    )
    connection: Optional[constr(max_length=255)] = Field(
        None,
        description='The connection string for the challenge. This is applicable if the `type` is not `instanced` and the challenge is hosted on a server. It is used to display connection information for the challenge. You can use the variable `${host}` in the string, which will be replaced with the website domain when rendered.',
        examples=['http://example.com', 'nc example.com 1337', 'nc ${host} 1337'],
    )
    points: Optional[conint(ge=1, le=10000)] = Field(
        1000, description='The amount of points the challenge is worth from the start'
    )
    decay: Optional[conint(ge=0, le=10000)] = Field(
        75, description='The percentage of points lost over time'
    )
    min_points: Optional[conint(ge=1, le=1000)] = Field(
        100,
        description='The minimum amount of points the challenge can be worth. min_points must be less than or equal to points.',
    )
    flag: Union[
        constr(
            regex=r'^(\w{2,10}\{[^}]*\}|dynamic|null)$', min_length=4, max_length=1000
        ),
        List[
            Union[
                constr(
                    regex=r'^(\w{2,10}\{[^}]*\}|dynamic|null)$',
                    min_length=4,
                    max_length=1000,
                ),
                Flag,
            ]
        ],
    ] = Field(
        ...,
        description="The flag of the challenge. May be a single string or an array of strings. Each may be 'dynamic', 'null', or a flag like 'flag{...}'. `flag` may be replaced with between 2 and 10 word chars. If case sensitivity is not explicitly specified, the flag is case sensitive.",
        examples=[
            'flag{flag}',
            ['flag{flag1}', 'flag{flag2}'],
            [
                {'flag': 'flag{flag1}', 'case_sensitive': True},
                {'flag': 'flag{flag2}', 'case_sensitive': False},
            ],
        ],
    )
    description_location: Optional[constr(regex=r'^[a-zA-Z0-9-_/.]+\.md$')] = Field(
        'description.md',
        description='The location of the description file relative to the challenge directory',
        examples=['description.md'],
    )
    dockerfile_locations: Optional[List[DockerfileLocation]] = Field(
        [],
        description='The locations of the Dockerfiles relative to the challenge directory.\nMultiple Dockerfiles can be specified if the challenge requires multiple images.',
    )
    handout_dir: Optional[constr(regex=r'^[a-zA-Z0-9-_/]+$')] = Field(
        'handout',
        description='The location of the handout directory relative to the challenge directory. Handout directory contains all files that are handed out to users (zipped to a single file that are stored in <category>_<slug>.zip in the files directory).',
        examples=['handout'],
    )
